- name: Sample playbook
  hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
  - name: Wait for all nodes to become ready
    wait_for_connection:
      delay: 5
      timeout: 60
  - name: Wait for cloud-init to finish
    raw: test -f /var/lib/cloud/instance/boot-finished
    retries: 12
    delay: 5
    register: result
    until: result.rc == 0
    changed_when: false
  - name: Gather facts
    setup:
  tasks:
  - ping:
